import { db, pollsTable, pollOptionsTable, profilesTable } from "@workspace/db";

async function seed() {
  console.log("Seeding database...");

  await db.delete(pollOptionsTable);
  await db.delete(pollsTable);
  await db.delete(profilesTable);

  // ── Profiles ─────────────────────────────────────────────────────────────────
  const profiles = await db.insert(profilesTable).values([
    {
      name: "Sultan Al Darmaki",
      headline: "Founder of 1833 Members Club — redefining what membership means in the Middle East",
      role: "Founder", company: "1833 Members Club", sector: "Community & Networking",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Sultan built 1833 Members Club in 2022, now with 1,800+ on the waiting list. A former luxury fashion founder (Darmaki footwear, featured at London Fashion Week), he created a private members community that champions collaboration over exclusivity.",
      story: "Sultan built 1833 Members Club in 2022, now with 1,800+ on the waiting list. A former luxury fashion founder (Darmaki footwear, featured at London Fashion Week), he created a private members community that champions collaboration over exclusivity.",
      lessonsLearned: [], quote: "Don't aim to replicate success — aim to redefine it.",
      isFeatured: true, isVerified: true, viewCount: 8200, associatedPollCount: 4,
    },
    {
      name: "Mohammed Al Zaben",
      headline: "Built MUNCH:ON and sold it to Careem — the man who made corporate lunch a tech problem worth solving",
      role: "Founder", company: "MUNCH:ON (acquired by Careem)", sector: "Food Tech",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Mohammed co-founded MUNCH:ON, transforming corporate food delivery in the Gulf until Careem acquired it in 2022.",
      story: "Mohammed co-founded MUNCH:ON, transforming corporate food delivery in the Gulf until Careem acquired it in 2022.",
      lessonsLearned: [], quote: "Don't chase trends. Build something that can sail smoothly for years.",
      isFeatured: true, isVerified: true, viewCount: 9100, associatedPollCount: 3,
    },
    {
      name: "Raya Bidshahri",
      headline: "Neuroscientist turned education innovator — reimagining how the world learns",
      role: "Founder & CEO", company: "School of Humanity", sector: "Education & Learning",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Raya founded the School of Humanity to replace memorization-based education with critical thinking, emotional intelligence, and interdisciplinary learning.",
      story: "Raya founded the School of Humanity to replace memorization-based education with critical thinking, emotional intelligence, and interdisciplinary learning.",
      lessonsLearned: [], quote: "Design education that inspires and equips learners to navigate an uncertain future confidently.",
      isFeatured: false, isVerified: true, viewCount: 5800, associatedPollCount: 5,
    },
    {
      name: "Talal Tabbaa",
      headline: "Making crypto accessible, compliant, and real for 400 million Arabs",
      role: "Co-Founder & CEO", company: "CoinMENA", sector: "Fintech",
      country: "Bahrain", city: "Manama", imageUrl: null,
      summary: "Talal co-founded CoinMENA, the MENA region's leading regulated crypto exchange, licensed by the Central Bank of Bahrain.",
      story: "Talal co-founded CoinMENA, the MENA region's leading regulated crypto exchange, licensed by the Central Bank of Bahrain.",
      lessonsLearned: [], quote: "To unlock the potential of crypto, start with trust.",
      isFeatured: false, isVerified: true, viewCount: 4200, associatedPollCount: 3,
    },
    {
      name: "Walid Daniel Dib",
      headline: "Destigmatizing men's health in the Arab world, one supplement at a time",
      role: "Co-Founder", company: "Better (itsbetter.app)", sector: "Health & Wellness",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Walid co-founded Better in 2024, targeting 10 million Arab men with personalized wellness solutions addressing sensitive health challenges.",
      story: "Walid co-founded Better in 2024, targeting 10 million Arab men with personalized wellness solutions addressing sensitive health challenges.",
      lessonsLearned: [], quote: "Focus on making a real difference in your customers' lives.",
      isFeatured: false, isVerified: true, viewCount: 3100, associatedPollCount: 2,
    },
    {
      name: "Ghaith Abdul Rahman",
      headline: "Senior Manager at Dubai Future Foundation — building the innovation infrastructure for tomorrow's city",
      role: "Senior Manager", company: "Dubai Future Foundation", sector: "Technology & AI",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Ghaith spent 15+ years across PwC, the Executive Office of HH Sheikh Mohammed bin Rashid, and Techstars before joining Dubai Future Foundation to drive urban and government innovation.",
      story: "Ghaith spent 15+ years across PwC, the Executive Office of HH Sheikh Mohammed bin Rashid, and Techstars before joining Dubai Future Foundation to drive urban and government innovation.",
      lessonsLearned: [], quote: "Real innovation isn't a showcase of trinkets — it's about testing the new to change the old.",
      isFeatured: false, isVerified: true, viewCount: 4700, associatedPollCount: 6,
    },
    {
      name: "Walid Faza",
      headline: "Partner & COO at MSA Capital — one of MENA's most active emerging market VC funds",
      role: "Partner & COO", company: "MSA Capital / MSA Novo", sector: "Venture & Startups",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Walid has spent a decade in MENA venture capital, previously at Wamda Capital, now at MSA Capital backing high-potential startups across emerging markets.",
      story: "Walid has spent a decade in MENA venture capital, previously at Wamda Capital, now at MSA Capital backing high-potential startups across emerging markets.",
      lessonsLearned: [], quote: "Success in emerging markets requires resilience, local insight, and the ability to transform obstacles into opportunities.",
      isFeatured: true, isVerified: true, viewCount: 7300, associatedPollCount: 7,
    },
    {
      name: "Majid Al Ansari",
      headline: "The Emirati filmmaker putting Gulf cinema on the global map",
      role: "Filmmaker & Director", company: "Independent", sector: "Media & Content",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Majid directed Zinzana (Rattle the Cage), one of the first Emirati films to premiere internationally, and has collaborated with Netflix to bring Emirati narratives to global screens.",
      story: "Majid directed Zinzana (Rattle the Cage), one of the first Emirati films to premiere internationally, and has collaborated with Netflix to bring Emirati narratives to global screens.",
      lessonsLearned: [], quote: "Stories are universal; find the heart of yours, and it will resonate anywhere.",
      isFeatured: false, isVerified: true, viewCount: 5100, associatedPollCount: 3,
    },
    {
      name: "Mohammad Al Razaz",
      headline: "Co-founder of OTO — the logistics platform powering MENA e-commerce",
      role: "Co-Founder", company: "OTO (tryoto.com)", sector: "Logistics & E-commerce",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Mohammad co-founded OTO in 2019, building a platform integrating 200+ carriers to help MENA retailers manage shipping, tracking, and returns from one dashboard.",
      story: "Mohammad co-founded OTO in 2019, building a platform integrating 200+ carriers to help MENA retailers manage shipping, tracking, and returns from one dashboard.",
      lessonsLearned: [], quote: "Focus on the details that matter most to your customers.",
      isFeatured: false, isVerified: true, viewCount: 3400, associatedPollCount: 2,
    },
    {
      name: "Khalid Al-Muflehi",
      headline: "The man who brought the NBA to Abu Dhabi",
      role: "Sports Unit Head", company: "Department of Culture & Tourism Abu Dhabi", sector: "Sports & Events",
      country: "UAE", city: "Abu Dhabi", imageUrl: null,
      summary: "Khalid has spent 15+ years positioning Abu Dhabi as a global sports tourism hub, leading landmark deals including bringing NBA games to the UAE.",
      story: "Khalid has spent 15+ years positioning Abu Dhabi as a global sports tourism hub, leading landmark deals including bringing NBA games to the UAE.",
      lessonsLearned: [], quote: "Focus on authenticity and excellence, and the world will take notice.",
      isFeatured: false, isVerified: true, viewCount: 4800, associatedPollCount: 2,
    },
    {
      name: "Bader Ataya",
      headline: "Co-Founder of Kitopi — turning cloud kitchens into a food revolution across 5 countries",
      role: "Co-Founder & Chief Growth Officer", company: "Kitopi", sector: "Food Tech",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Bader co-founded Kitopi, which has grown to 200+ locations and 6,000+ employees across 5 markets, redefining homegrown food brands in the region.",
      story: "Bader co-founded Kitopi, which has grown to 200+ locations and 6,000+ employees across 5 markets, redefining homegrown food brands in the region.",
      lessonsLearned: [], quote: "Think creatively about solving industry challenges.",
      isFeatured: true, isVerified: true, viewCount: 8900, associatedPollCount: 4,
    },
    {
      name: "Muhannad Al Shami",
      headline: "From PwC associate to partner in 13 years — the long game of corporate excellence",
      role: "Partner, Management Consulting", company: "PwC", sector: "Consulting",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Muhannad rose from associate to partner at PwC over 13 years, advising governments and enterprises on complex transformations.",
      story: "Muhannad rose from associate to partner at PwC over 13 years, advising governments and enterprises on complex transformations.",
      lessonsLearned: [], quote: "Success is a marathon, not a sprint.",
      isFeatured: false, isVerified: true, viewCount: 2900, associatedPollCount: 3,
    },
    {
      name: "Kunaal Kapur",
      headline: "Director of Corporate Finance at Arena Group — from oil & gas to running finance for the Paris Olympics",
      role: "Director, Corporate Finance & Treasury", company: "Arena Group", sector: "Finance",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Kunaal has 16+ years across oil & gas, Abu Dhabi Airports, and major events finance, most recently leading the Finance Team for Arena Group at the Paris Olympics.",
      story: "Kunaal has 16+ years across oil & gas, Abu Dhabi Airports, and major events finance, most recently leading the Finance Team for Arena Group at the Paris Olympics.",
      lessonsLearned: [], quote: "Financial leadership is about understanding the story behind the numbers.",
      isFeatured: false, isVerified: true, viewCount: 2700, associatedPollCount: 2,
    },
    {
      name: "Saad Abu Touq",
      headline: "Managing Director of PR at Ogilvy UAE — 14 years building the region's most impactful campaigns",
      role: "Managing Director, Public Relations", company: "Ogilvy UAE", sector: "Media & Marketing",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Saad led Ogilvy UAE to double-digit growth over 14 years, delivering award-winning campaigns across the UAE, KSA, and Jordan. Board member of MEPRA.",
      story: "Saad led Ogilvy UAE to double-digit growth over 14 years, delivering award-winning campaigns across the UAE, KSA, and Jordan. Board member of MEPRA.",
      lessonsLearned: [], quote: "In the business of influence and impact, your team is your real asset.",
      isFeatured: false, isVerified: true, viewCount: 3600, associatedPollCount: 3,
    },
    {
      name: "Saad Abu Zahra",
      headline: "Senior Account Manager at Autodesk — modernizing how the Middle East builds",
      role: "Enterprise Sales", company: "Autodesk", sector: "Technology",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Saad helps large MENA enterprises transform through digital solutions at Autodesk, previously a digital transformation advisor at PwC.",
      story: "Saad helps large MENA enterprises transform through digital solutions at Autodesk, previously a digital transformation advisor at PwC.",
      lessonsLearned: [], quote: "Growth doesn't happen by accident; it's the product of strategy, persistence, and a willingness to embrace change.",
      isFeatured: false, isVerified: false, viewCount: 2100, associatedPollCount: 2,
    },
    {
      name: "Ramzi Farah",
      headline: "Managing Partner at Razor Capital — investing with impact in Lebanon, Bangladesh, and beyond",
      role: "Managing Partner", company: "Razor Capital", sector: "Venture & Startups",
      country: "Lebanon", city: "Beirut", imageUrl: null,
      summary: "Ramzi leads Razor Capital, backing high-growth startups across MENA and beyond with a focus on social impact alongside commercial returns.",
      story: "Ramzi leads Razor Capital, backing high-growth startups across MENA and beyond with a focus on social impact alongside commercial returns.",
      lessonsLearned: [], quote: "Look beyond immediate returns. Focus on building companies that address real needs.",
      isFeatured: false, isVerified: true, viewCount: 3200, associatedPollCount: 3,
    },
    {
      name: "Loulou Khazen Baz",
      headline: "Founder of Conversations with Loulou and Spade Ventures — amplifying MENA's entrepreneurial voices",
      role: "Founder", company: "Conversations with Loulou / Spade Ventures", sector: "Media & Startups",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Loulou hosts one of MENA's most listened-to entrepreneurship platforms while actively investing in regional startups through Spade Ventures.",
      story: "Loulou hosts one of MENA's most listened-to entrepreneurship platforms while actively investing in regional startups through Spade Ventures.",
      lessonsLearned: [], quote: "Creating a platform is more than building a brand; it's about fostering a community that learns and grows together.",
      isFeatured: true, isVerified: true, viewCount: 11200, associatedPollCount: 5,
    },
    {
      name: "Aya Sadder",
      headline: "Founder of Bolt Consultancy — 10+ years building MENA's startup ecosystem through Techstars and beyond",
      role: "Founder & CEO", company: "Bolt Consultancy", sector: "Innovation & Ecosystems",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Aya has spent over a decade mentoring founders globally through Techstars, the Mohammed Bin Rashid Innovation Fund, and Intelak Hub, while running Bolt Consultancy.",
      story: "Aya has spent over a decade mentoring founders globally through Techstars, the Mohammed Bin Rashid Innovation Fund, and Intelak Hub, while running Bolt Consultancy.",
      lessonsLearned: [], quote: "Collaboration is the key to innovation.",
      isFeatured: false, isVerified: true, viewCount: 3800, associatedPollCount: 3,
    },
    {
      name: "Fadi Kanaan",
      headline: "Co-founder of EAGLE AI — bringing INTERPOL-grade crowd intelligence to the Middle East's biggest events",
      role: "Co-Founder", company: "EAGLE AI", sector: "Technology & AI",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Fadi built EAGLE AI to provide real-time crowd mapping and management, drawing on experience at INTERPOL, the UN, and NAUSS.",
      story: "Fadi built EAGLE AI to provide real-time crowd mapping and management, drawing on experience at INTERPOL, the UN, and NAUSS.",
      lessonsLearned: [], quote: "Leverage technology, but never underestimate the value of people.",
      isFeatured: false, isVerified: true, viewCount: 4100, associatedPollCount: 4,
    },
    {
      name: "Nada Khan",
      headline: "Regional Marketing Director at Nutanix — driving cloud adoption across the Middle East, Turkey and Africa",
      role: "Regional Marketing Director", company: "Nutanix", sector: "Technology",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Nada leads Nutanix's emerging markets marketing team, previously at LinkedIn, building culturally resonant campaigns across 4 continents.",
      story: "Nada leads Nutanix's emerging markets marketing team, previously at LinkedIn, building culturally resonant campaigns across 4 continents.",
      lessonsLearned: [], quote: "Great marketing is about connecting authentically with people and cultures.",
      isFeatured: false, isVerified: false, viewCount: 2400, associatedPollCount: 2,
    },
    {
      name: "Dana Baki",
      headline: "Co-founded MUNCH:ON, sold it, then went to work on outer space — that's a career arc",
      role: "Chief Commercial Officer", company: "Exploration Space", sector: "Food Tech & Space Tech",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Dana co-founded MUNCH:ON (acquired by Careem), then pivoted to Chief Commercial Officer at Exploration Space, making her one of the few MENA entrepreneurs crossing into the space economy.",
      story: "Dana co-founded MUNCH:ON (acquired by Careem), then pivoted to Chief Commercial Officer at Exploration Space, making her one of the few MENA entrepreneurs crossing into the space economy.",
      lessonsLearned: [], quote: "Don't hesitate to dare — you'll be surprised what becomes possible when you just believe it is.",
      isFeatured: true, isVerified: true, viewCount: 7600, associatedPollCount: 3,
    },
    {
      name: "Maher Kaddoura",
      headline: "Middle East's first Accenture Managing Partner. 200,000 lives impacted. Author of The Falafel Theory. Don't live half a life.",
      role: "Visionary Leader, Author & Social Impact Pioneer", company: "Al Jude NGO / Hikmat", sector: "Leadership & Social Impact",
      country: "Jordan", city: "Amman", imageUrl: null,
      summary: "Maher spent 40+ years at Accenture before pivoting to social impact, building 1,200+ playgrounds in Jordanian public schools and impacting 200,000+ lives through Al Jude NGO and Hikmat. Author, adventurer, and board member of Endeavor.",
      story: "Maher spent 40+ years at Accenture before pivoting to social impact, building 1,200+ playgrounds in Jordanian public schools and impacting 200,000+ lives through Al Jude NGO and Hikmat. Author, adventurer, and board member of Endeavor.",
      lessonsLearned: [], quote: "Don't live half a life.",
      isFeatured: true, isVerified: true, viewCount: 12800, associatedPollCount: 6,
    },
    {
      name: "Badr Ward",
      headline: "CEO of Lamsa — the Arabic children's education platform reaching millions of families",
      role: "CEO", company: "Lamsa", sector: "Education & Learning",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Badr leads Lamsa, the first mobile education platform tailored for Arabic-speaking children, now partnering with ministries of education across the region.",
      story: "Badr leads Lamsa, the first mobile education platform tailored for Arabic-speaking children, now partnering with ministries of education across the region.",
      lessonsLearned: [], quote: "Children learn best when they are having fun. Always put the joy of discovery at the heart of education.",
      isFeatured: false, isVerified: true, viewCount: 4300, associatedPollCount: 3,
    },
    {
      name: "Nikita Sachdev Lord",
      headline: "Founder of Luna PR — making Web3 and fintech startups heard in a world that doesn't understand them yet",
      role: "Founder & CEO", company: "Luna PR", sector: "PR & Communications",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Nikita built Luna PR from a personal fascination with crypto into one of MENA's leading PR agencies for blockchain and fintech startups.",
      story: "Nikita built Luna PR from a personal fascination with crypto into one of MENA's leading PR agencies for blockchain and fintech startups.",
      lessonsLearned: [], quote: "Every revolutionary idea needs a compelling story to thrive.",
      isFeatured: false, isVerified: true, viewCount: 3700, associatedPollCount: 2,
    },
    {
      name: "Karima El Hakim",
      headline: "Country Director for Egypt at Plug and Play — championing Arab and African startup ecosystems",
      role: "Country Director, Egypt & Africa Ventures", company: "Plug and Play", sector: "Venture & Startups",
      country: "Egypt", city: "Cairo", imageUrl: null,
      summary: "Karima connects founders, corporates, and capital across Africa and the Arab world. Previously at Orascom and Fawry, now on Egypt's National Council for Women Economic Committee.",
      story: "Karima connects founders, corporates, and capital across Africa and the Arab world. Previously at Orascom and Fawry, now on Egypt's National Council for Women Economic Committee.",
      lessonsLearned: [], quote: "Great ecosystems don't happen by chance — they are built with intention, collaboration, and a deep understanding of local markets.",
      isFeatured: true, isVerified: true, viewCount: 8400, associatedPollCount: 5,
    },
    {
      name: "Laith Zraikat",
      headline: "Dentist. Founder. VC. 9 exits. Now building again in stealth.",
      role: "Founder (Stealth) / Former Partner", company: "Arzan Venture Capital", sector: "Venture & Startups",
      country: "Jordan", city: "Amman", imageUrl: null,
      summary: "Laith co-founded Jeeran (the Arab world's first social network), then backed 40+ startups at Arzan VC including Mejuri, Trukker, and Zid (combined $2B+ value). Now building his next venture.",
      story: "Laith co-founded Jeeran (the Arab world's first social network), then backed 40+ startups at Arzan VC including Mejuri, Trukker, and Zid (combined $2B+ value). Now building his next venture.",
      lessonsLearned: [], quote: "Great products don't just solve problems — they create habits. Build something people can't live without.",
      isFeatured: true, isVerified: true, viewCount: 9600, associatedPollCount: 7,
    },
    {
      name: "Amjad Masad",
      headline: "Founder & CEO of Replit — the Jordanian who made coding accessible to the entire world",
      role: "Founder & CEO", company: "Replit", sector: "Technology & AI",
      country: "USA (Jordanian)", city: "San Francisco", imageUrl: null,
      summary: "Amjad grew up in Amman, worked at Yahoo, Codecademy, and Facebook, then built Replit into a global platform with millions of users redefining how software is created — now with AI at its core.",
      story: "Amjad grew up in Amman, worked at Yahoo, Codecademy, and Facebook, then built Replit into a global platform with millions of users redefining how software is created — now with AI at its core.",
      lessonsLearned: [], quote: "The best way to predict the future? Build the tools that create it.",
      isFeatured: true, isVerified: true, viewCount: 14200, associatedPollCount: 8,
    },
    {
      name: "Sarah Toukan",
      headline: "Co-Founder & CPO of Ziina — building the UAE's future of peer-to-peer payments",
      role: "Co-Founder & Chief Product Officer", company: "Ziina", sector: "Fintech",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Sarah co-founded Ziina, the UAE's first Y Combinator-backed fintech, bringing Stanford design thinking to digital payments in the Middle East.",
      story: "Sarah co-founded Ziina, the UAE's first Y Combinator-backed fintech, bringing Stanford design thinking to digital payments in the Middle East.",
      lessonsLearned: [], quote: "Keep the user at the heart of every decision.",
      isFeatured: false, isVerified: true, viewCount: 4500, associatedPollCount: 3,
    },
    {
      name: "Faisal Toukan",
      headline: "Co-Founder & CEO of Ziina — the first P2P payment platform licensed by the UAE Central Bank",
      role: "Co-Founder & CEO", company: "Ziina", sector: "Fintech",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Faisal built Ziina from the ground up, securing UAE Central Bank licensing and Y Combinator backing — transforming how payments work in the region.",
      story: "Faisal built Ziina from the ground up, securing UAE Central Bank licensing and Y Combinator backing — transforming how payments work in the region.",
      lessonsLearned: [], quote: "Simplify user challenges and work with regulators to balance innovation and trust.",
      isFeatured: false, isVerified: true, viewCount: 4200, associatedPollCount: 3,
    },
    {
      name: "Dina Sam'an",
      headline: "Co-Founder of CoinMENA — Forbes 30 Under 30, youngest board member at her university, and building crypto access for all Arabs",
      role: "Co-Founder & Managing Director", company: "CoinMENA", sector: "Fintech",
      country: "UAE/Bahrain", city: "Dubai", imageUrl: null,
      summary: "Dina co-founded CoinMENA in 2019 with CBB and VARA regulatory approval, growing it into one of MENA's most trusted crypto platforms. Forbes 30 Under 30.",
      story: "Dina co-founded CoinMENA in 2019 with CBB and VARA regulatory approval, growing it into one of MENA's most trusted crypto platforms. Forbes 30 Under 30.",
      lessonsLearned: [], quote: "Crypto isn't just about speculation — it's about financial freedom.",
      isFeatured: true, isVerified: true, viewCount: 7900, associatedPollCount: 4,
    },
    {
      name: "Omar Absi",
      headline: "Co-Founder of Swftbox — from Pizza Hut campaigns to building MENA's AI-powered last-mile delivery network",
      role: "Co-Founder & Head of Marketing", company: "Swftbox", sector: "Logistics Tech",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Omar co-founded Swftbox in 2019, applying his brand marketing expertise to build a smart logistics platform that's reshaping how e-commerce brands fulfill orders across MENA.",
      story: "Omar co-founded Swftbox in 2019, applying his brand marketing expertise to build a smart logistics platform that's reshaping how e-commerce brands fulfill orders across MENA.",
      lessonsLearned: [], quote: "The best businesses aren't built on ideas alone — they're built on execution, scale, and relentless improvement.",
      isFeatured: false, isVerified: true, viewCount: 3300, associatedPollCount: 2,
    },
    {
      name: "Mark Chahwan",
      headline: "Co-Founder & CEO of Sarwa — AED 10 billion in trading volume and making investing accessible to every Arab",
      role: "Co-Founder & Group CEO", company: "Sarwa", sector: "Fintech",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Mark built Sarwa from zero to AED 10B+ in trading volume, becoming MENA's leading wealth management platform — profitable in 2024 and backed by Mubadala and ADQ.",
      story: "Mark built Sarwa from zero to AED 10B+ in trading volume, becoming MENA's leading wealth management platform — profitable in 2024 and backed by Mubadala and ADQ.",
      lessonsLearned: [], quote: "Wealth-building isn't just for the elite. Give people access, remove the friction, and let them thrive.",
      isFeatured: true, isVerified: true, viewCount: 10100, associatedPollCount: 5,
    },
    {
      name: "Abe Seksek",
      headline: "The guy behind the scene — 700+ founders supported, 9 boards, and still building quietly",
      role: "Founder / Operator / Investor / CEO", company: "Startupbootcamp MENA & Africa", sector: "Venture & Startups",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Abe co-founded Jordan's first BPO, scaled Dubizzle to 300M+ monthly page views, co-founded ZenHR, and has since supported 700+ founders through Startupbootcamp. Quietly one of MENA's most influential operators.",
      story: "Abe co-founded Jordan's first BPO, scaled Dubizzle to 300M+ monthly page views, co-founded ZenHR, and has since supported 700+ founders through Startupbootcamp. Quietly one of MENA's most influential operators.",
      lessonsLearned: [], quote: "Build quietly. Scale loudly.",
      isFeatured: true, isVerified: true, viewCount: 11500, associatedPollCount: 8,
    },
    {
      name: "Malak Albaw",
      headline: "Left home at 17, helped raise $5M by 21, became COO at 22 — now building Alba Ventures",
      role: "Founder & CEO", company: "Alba Ventures", sector: "Web3 & Growth Strategy",
      country: "UAE", city: "Abu Dhabi", imageUrl: null,
      summary: "Malak moved from the Middle East to Venice at 17, rose to COO of a startup that was acquired in 16 months, then pivoted to Web3 PR and founded Alba Ventures, advising bold startups on funding and visibility.",
      story: "Malak moved from the Middle East to Venice at 17, rose to COO of a startup that was acquired in 16 months, then pivoted to Web3 PR and founded Alba Ventures, advising bold startups on funding and visibility.",
      lessonsLearned: [], quote: "Don't just raise money. Raise eyebrows.",
      isFeatured: false, isVerified: true, viewCount: 5400, associatedPollCount: 3,
    },
    {
      name: "Dr. Sara Althari",
      headline: "Oxford genomics PhD. Saudi biotech policy architect. Founder of The Althari Group.",
      role: "Founder & Managing Partner", company: "The Althari Group (TAG)", sector: "Deep Tech & Policy",
      country: "Saudi Arabia", city: "Riyadh", imageUrl: null,
      summary: "Sara trained in genomics at Oxford and the Broad Institute (MIT/Harvard), then led biotech and pharma strategy at Saudi Arabia's Ministry of Investment. Now advises governments and frontier tech founders through TAG.",
      story: "Sara trained in genomics at Oxford and the Broad Institute (MIT/Harvard), then led biotech and pharma strategy at Saudi Arabia's Ministry of Investment. Now advises governments and frontier tech founders through TAG.",
      lessonsLearned: [], quote: "You don't have to choose between ambition and integrity. Build both.",
      isFeatured: true, isVerified: true, viewCount: 9200, associatedPollCount: 4,
    },
    {
      name: "Dr. Ajlan Al Zaki",
      headline: "Trained at Stanford and MD Anderson. Came home to make cutting-edge cancer therapy affordable in the Arab world.",
      role: "Director, Hematology Oncology & Cellular Therapy Center", company: "Burjeel", sector: "Healthcare & Life Sciences",
      country: "UAE", city: "Abu Dhabi", imageUrl: null,
      summary: "Ajlan completed MD/PhD training across Stanford, MD Anderson, and UPenn, then returned to the UAE to build a CAR T cell therapy center at Burjeel — making world-class cancer treatment accessible and affordable regionally.",
      story: "Ajlan completed MD/PhD training across Stanford, MD Anderson, and UPenn, then returned to the UAE to build a CAR T cell therapy center at Burjeel — making world-class cancer treatment accessible and affordable regionally.",
      lessonsLearned: [], quote: "We talk about precision medicine. The real precision is knowing where it matters most.",
      isFeatured: true, isVerified: true, viewCount: 8700, associatedPollCount: 2,
    },
    {
      name: "Mohamed (Nagaty) Aboulnaga",
      headline: "Co-Founder of Exits MENA — building the liquidity infrastructure the region's startup ecosystem has been missing",
      role: "Co-Founder & Executive Chairman", company: "Exits MENA", sector: "Venture & Startups",
      country: "Egypt", city: "Cairo", imageUrl: null,
      summary: "Mohamed has spent two decades building companies and NGOs across continents, now focusing on unlocking acquisition opportunities and liquidity for MENA startups through Exits MENA.",
      story: "Mohamed has spent two decades building companies and NGOs across continents, now focusing on unlocking acquisition opportunities and liquidity for MENA startups through Exits MENA.",
      lessonsLearned: [], quote: "Put your head down, build something real, and let the rest chase headlines.",
      isFeatured: false, isVerified: true, viewCount: 5800, associatedPollCount: 5,
    },
    {
      name: "Anis Harb",
      headline: "Deliveroo's first hire in the Middle East — built it from zero to millions of orders",
      role: "Former VP & Middle East GM", company: "Deliveroo", sector: "Food Tech & Operations",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Anis was Deliveroo's first Middle East hire, spending 10 years building the platform from a one-man launch to a regional category leader. Previously at Amazon (London) and J.P. Morgan.",
      story: "Anis was Deliveroo's first Middle East hire, spending 10 years building the platform from a one-man launch to a regional category leader. Previously at Amazon (London) and J.P. Morgan.",
      lessonsLearned: [], quote: "The best brands don't just deliver food. They deliver consistency.",
      isFeatured: true, isVerified: true, viewCount: 9800, associatedPollCount: 3,
    },
    {
      name: "Mazen Kanaan",
      headline: "Built House of Pops from a three-wheeler cart to 1,000+ distribution points in 5 countries — popsicles with a purpose",
      role: "Co-Founder & CEO", company: "House of Pops", sector: "F&B & Brand Building",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Mazen started House of Pops in 2018 with a three-wheeler and obsessive product focus, growing it into a clean-ingredients lifestyle brand franchised across 5 countries.",
      story: "Mazen started House of Pops in 2018 with a three-wheeler and obsessive product focus, growing it into a clean-ingredients lifestyle brand franchised across 5 countries.",
      lessonsLearned: [], quote: "Don't chase trends. Build something timeless, then let people catch up.",
      isFeatured: false, isVerified: true, viewCount: 4600, associatedPollCount: 2,
    },
    {
      name: "Sara Hamdan",
      headline: "From Merrill Lynch to The New York Times to the first two-book deal with a Big 5 publisher from the Middle East",
      role: "Author, Editor & Moderator", company: "bySaraHamdan", sector: "Media & Storytelling",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Sara is the first contemporary Middle Eastern woman to land a two-book fiction deal with a Big 5 US publisher (Holt). Former NYT journalist, Editor-in-Chief of Think with Google MENA, and 2024 Netflix award winner.",
      story: "Sara is the first contemporary Middle Eastern woman to land a two-book fiction deal with a Big 5 US publisher (Holt). Former NYT journalist, Editor-in-Chief of Think with Google MENA, and 2024 Netflix award winner.",
      lessonsLearned: [], quote: "Tell the story only you can tell. That's where the magic is.",
      isFeatured: true, isVerified: true, viewCount: 10400, associatedPollCount: 4,
    },
    {
      name: "Nader Baker",
      headline: "Co-founder of Misfits — the agency whose campaigns get reshared by Elon Musk and Snoop Dogg",
      role: "Co-Founder", company: "Misfits", sector: "Creative Marketing",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Nader co-founded Misfits in 2015 after years at Impact BBDO and Havas, building a creative agency that prioritizes bold storytelling over volume. Their campaigns have gone globally viral.",
      story: "Nader co-founded Misfits in 2015 after years at Impact BBDO and Havas, building a creative agency that prioritizes bold storytelling over volume. Their campaigns have gone globally viral.",
      lessonsLearned: [], quote: "If you have something to say — say it in a way that will make them want to listen.",
      isFeatured: false, isVerified: true, viewCount: 6200, associatedPollCount: 3,
    },
    {
      name: "Rami Salman",
      headline: "Built Wrappup at 13, sold it to Cisco via Voicea, scaled Vidcast to 1M users — now investing in what's next",
      role: "GM of Vidcast at Cisco / Co-Founder of Wrappup", company: "Cisco / Wrappup (Acquired)", sector: "AI & Enterprise Tech",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Rami founded his first company at 13, built Wrappup (AI meeting summaries) which was acquired by Voicea then Cisco, and scaled Vidcast to 1M+ users in one year. Now advising and investing.",
      story: "Rami founded his first company at 13, built Wrappup (AI meeting summaries) which was acquired by Voicea then Cisco, and scaled Vidcast to 1M+ users in one year. Now advising and investing.",
      lessonsLearned: [], quote: "Success isn't about ideas. It's about executing with the team who can turn them into products that matter.",
      isFeatured: true, isVerified: true, viewCount: 8300, associatedPollCount: 5,
    },
    {
      name: "Mousa Yassin",
      headline: "From BP supply chains to frontline worker training — Founder of Pixaera, reimagining safety at work",
      role: "Founder & CEO", company: "Pixaera", sector: "EHS Tech & Training",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Mousa started at BP managing complex supply chains, co-founded Geeks.ae, then founded Pixaera to build immersive VR training tools for frontline EHS workers. Also hosts the Safety Heroes podcast.",
      story: "Mousa started at BP managing complex supply chains, co-founded Geeks.ae, then founded Pixaera to build immersive VR training tools for frontline EHS workers. Also hosts the Safety Heroes podcast.",
      lessonsLearned: [], quote: "If tech doesn't reach the worker on the ground, it's not innovation. It's just noise.",
      isFeatured: false, isVerified: true, viewCount: 3900, associatedPollCount: 2,
    },
    {
      name: "Tala Al Jabri",
      headline: "Founder of Wyld VC — bridging Gulf capital and Silicon Valley's AI-native founders",
      role: "Founder & Managing Partner", company: "Wyld VC", sector: "Venture Capital & AI",
      country: "Saudi Arabia", city: "Riyadh", imageUrl: null,
      summary: "Tala formerly invested at SoftBank Vision Fund and Andreessen Horowitz, now runs Wyld VC backing AI-native founders. Harvard Kennedy School and Wharton graduate. Advisory Council member at Harvard's Mossavar-Rahmani Center.",
      story: "Tala formerly invested at SoftBank Vision Fund and Andreessen Horowitz, now runs Wyld VC backing AI-native founders. Harvard Kennedy School and Wharton graduate. Advisory Council member at Harvard's Mossavar-Rahmani Center.",
      lessonsLearned: [], quote: "Think differently, challenge your assumptions.",
      isFeatured: true, isVerified: true, viewCount: 12100, associatedPollCount: 7,
    },
    {
      name: "Nafez Dakkak",
      headline: "Built Edraak to 10M learners. Now deploying impact capital through Anara — from classrooms to capital.",
      role: "Managing Partner", company: "Anara Impact Capital", sector: "Education & Impact Investing",
      country: "Jordan", city: "Amman", imageUrl: null,
      summary: "Nafez was founding CEO of Edraak (Queen Rania Foundation), grew it to 10M+ learners, co-founded BLDR Ventures, and now leads Anara Impact Capital funding human development ventures.",
      story: "Nafez was founding CEO of Edraak (Queen Rania Foundation), grew it to 10M+ learners, co-founded BLDR Ventures, and now leads Anara Impact Capital funding human development ventures.",
      lessonsLearned: [], quote: "Listen first. Design second. Scale last.",
      isFeatured: false, isVerified: true, viewCount: 5200, associatedPollCount: 4,
    },
    {
      name: "Ryan Bistany",
      headline: "Director at SABIS — scaling one of the world's oldest education networks to 20 countries including Shanghai",
      role: "Director", company: "SABIS", sector: "Education & Learning",
      country: "Lebanon", city: "Beirut", imageUrl: null,
      summary: "Ryan is part of SABIS's founding family, leading international expansion including the launch of a SABIS campus in Shanghai.",
      story: "Ryan is part of SABIS's founding family, leading international expansion including the launch of a SABIS campus in Shanghai.",
      lessonsLearned: [], quote: "Education is the most powerful tool we have to shape the future.",
      isFeatured: false, isVerified: false, viewCount: 2200, associatedPollCount: 2,
    },
    {
      name: "Nahla Atié",
      headline: "Creative Director of The Lighthouse — grew it from one location to five across the UAE",
      role: "Creative Director", company: "The Lighthouse", sector: "Retail & Lifestyle",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Nahla shaped The Lighthouse's identity from concept to a 5-location lifestyle concept blending dining, design, and community.",
      story: "Nahla shaped The Lighthouse's identity from concept to a 5-location lifestyle concept blending dining, design, and community.",
      lessonsLearned: [], quote: "Make your brand relatable and authentic — it's the stories and experiences that people connect with most.",
      isFeatured: false, isVerified: false, viewCount: 2800, associatedPollCount: 2,
    },
    {
      name: "Nishant Singh",
      headline: "VP of Strategic Partnerships at Crescent Enterprises — former Harvard Lakshmi Mittal Institute and Fulbright Scholar",
      role: "VP, Strategic Partnerships", company: "Crescent Enterprises", sector: "Social Impact & Philanthropy",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Nishant bridges private sector and societal impact across the Middle East, Africa, and South Asia. Former Chief Program Officer at Harvard's Lakshmi Mittal South Asia Institute and Fulbright Scholar.",
      story: "Nishant bridges private sector and societal impact across the Middle East, Africa, and South Asia. Former Chief Program Officer at Harvard's Lakshmi Mittal South Asia Institute and Fulbright Scholar.",
      lessonsLearned: [], quote: "Adapt to new environments with a growth mindset.",
      isFeatured: false, isVerified: true, viewCount: 3100, associatedPollCount: 2,
    },
    {
      name: "Majdy Miqdady",
      headline: "Co-Founder of Flan & UNICEF Communications Designer — where purpose meets platform",
      role: "Co-Founder & COO", company: "Flan / UNICEF Jordan", sector: "Technology & Design",
      country: "Jordan", city: "Amman", imageUrl: null,
      summary: "Majdy co-founded Flan, a human-centered social platform, while simultaneously serving as Communications Officer at UNICEF Jordan — applying design as a force for both commercial and humanitarian impact.",
      story: "Majdy co-founded Flan, a human-centered social platform, while simultaneously serving as Communications Officer at UNICEF Jordan — applying design as a force for both commercial and humanitarian impact.",
      lessonsLearned: [], quote: "Design is about more than visuals; it's about creating experiences that speak to people on a human level.",
      isFeatured: false, isVerified: true, viewCount: 2600, associatedPollCount: 2,
    },
    {
      name: "Ambareen Musa",
      headline: "CEO of Revolut UAE — founded Souqalmal before it was cool to make finance transparent for Arabs",
      role: "CEO", company: "Revolut UAE", sector: "Fintech",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Ambareen founded Souqalmal to democratize financial comparison in MENA, then became CEO of Revolut UAE, continuing her mission to make financial services accessible and clear.",
      story: "Ambareen founded Souqalmal to democratize financial comparison in MENA, then became CEO of Revolut UAE, continuing her mission to make financial services accessible and clear.",
      lessonsLearned: [], quote: "Financial literacy empowers individuals and communities; make transparency a core value.",
      isFeatured: true, isVerified: true, viewCount: 9300, associatedPollCount: 4,
    },
    {
      name: "Hamdan Al Khafaji",
      headline: "Founder of Contrast Wellness — redefining longevity and health in Dubai",
      role: "Founder", company: "Contrast Wellness", sector: "Health & Wellness",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Hamdan built Contrast as Dubai's holistic wellness studio combining thermal therapy with modern science, focused on sustainable long-term health rather than quick fixes.",
      story: "Hamdan built Contrast as Dubai's holistic wellness studio combining thermal therapy with modern science, focused on sustainable long-term health rather than quick fixes.",
      lessonsLearned: [], quote: "The most effective wellness practices are those you can stick with.",
      isFeatured: false, isVerified: false, viewCount: 2900, associatedPollCount: 2,
    },
    {
      name: "Maryam Al Hassani",
      headline: "Founder of Zealous — cutting software development costs by 70% and making tech accessible to everyone",
      role: "Founder & CEO", company: "Zealous", sector: "Technology & AI",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Maryam is a Forbes 30 Under 30 honoree and WEF Global Shaper who built Zealous to reduce software development timelines and costs by 70%, democratizing tech for underserved teams and startups.",
      story: "Maryam is a Forbes 30 Under 30 honoree and WEF Global Shaper who built Zealous to reduce software development timelines and costs by 70%, democratizing tech for underserved teams and startups.",
      lessonsLearned: [], quote: "True impact lies in enabling others. Build tools that help people create their own success stories.",
      isFeatured: true, isVerified: true, viewCount: 7100, associatedPollCount: 4,
    },
    {
      name: "Noelle Al-Jaweini",
      headline: "Chief of Cash Markets at Saudi Exchange — helping build one of the world's fastest-growing capital markets",
      role: "Chief of Cash Markets & Acting Chief of Derivatives", company: "Saudi Exchange", sector: "Finance & Capital Markets",
      country: "Saudi Arabia", city: "Riyadh", imageUrl: null,
      summary: "Noelle has spent 10+ years at the Saudi Exchange driving Vision 2030's capital markets transformation, launching Saudi Arabia's first derivatives market and attracting global institutional investors.",
      story: "Noelle has spent 10+ years at the Saudi Exchange driving Vision 2030's capital markets transformation, launching Saudi Arabia's first derivatives market and attracting global institutional investors.",
      lessonsLearned: [], quote: "Markets thrive when innovation meets collaboration.",
      isFeatured: true, isVerified: true, viewCount: 8600, associatedPollCount: 3,
    },
    {
      name: "Zeid Hreish",
      headline: "One of Uber MENA's first 5 hires. Scaled CloudKitchens. Now leading Web3 financial infrastructure for the region.",
      role: "General Manager, MENA", company: "Tools for Humanity (Worldcoin)", sector: "Technology & Web3",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Zeid launched Uber across Qatar, Bahrain, and Saudi Arabia, scaled CloudKitchens to secure a $400M PIF investment, and now leads Tools for Humanity (Worldcoin)'s MENA expansion.",
      story: "Zeid launched Uber across Qatar, Bahrain, and Saudi Arabia, scaled CloudKitchens to secure a $400M PIF investment, and now leads Tools for Humanity (Worldcoin)'s MENA expansion.",
      lessonsLearned: [], quote: "Disruption isn't just about technology — it's about execution, timing, and building for scale.",
      isFeatured: true, isVerified: true, viewCount: 9400, associatedPollCount: 4,
    },
    {
      name: "Fares Ghandour",
      headline: "Co-Founder of Tuhoon & Partner at Wamda Capital — tackling the mental health crisis no one talks about in MENA",
      role: "Co-Founder & CEO / Partner", company: "Tuhoon / Wamda Capital", sector: "Health Tech & Venture Capital",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Fares co-founded Tuhoon to bring culturally relevant mental health support to Arabic-speaking communities (85%+ lack adequate access), while continuing as a Partner at Wamda Capital backing MENA tech startups.",
      story: "Fares co-founded Tuhoon to bring culturally relevant mental health support to Arabic-speaking communities (85%+ lack adequate access), while continuing as a Partner at Wamda Capital backing MENA tech startups.",
      lessonsLearned: [], quote: "True impact comes from understanding the people you're building for.",
      isFeatured: true, isVerified: true, viewCount: 7800, associatedPollCount: 4,
    },
    {
      name: "Dania Shahin",
      headline: "Head of Strategy & Operations at Alpha Wave Global — from co-founding a startup to scaling 100s of them",
      role: "Head of Strategy and Operations", company: "Alpha Wave Global", sector: "Venture & Startups",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Dania co-founded Wekard, led Techstars' HUB71 Accelerator in Abu Dhabi, and now works with emerging tech companies at Alpha Wave Global helping them scale across MENA.",
      story: "Dania co-founded Wekard, led Techstars' HUB71 Accelerator in Abu Dhabi, and now works with emerging tech companies at Alpha Wave Global helping them scale across MENA.",
      lessonsLearned: [], quote: "Entering the MENA market requires a deep understanding of local cultures. Build authentic relationships.",
      isFeatured: false, isVerified: true, viewCount: 4100, associatedPollCount: 3,
    },
    {
      name: "Stephanie Emile",
      headline: "General Manager of Binance Dubai — from Barclays to BNP to rebuilding how money moves in the Middle East",
      role: "General Manager", company: "Binance FZE (Dubai)", sector: "Fintech & Digital Assets",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Stephanie moved from BNP Paribas and Barclays (London, New York, Dubai) into crypto regulation, becoming GM of Binance Dubai and one of the region's most credible voices on digital assets policy.",
      story: "Stephanie moved from BNP Paribas and Barclays (London, New York, Dubai) into crypto regulation, becoming GM of Binance Dubai and one of the region's most credible voices on digital assets policy.",
      lessonsLearned: [], quote: "You don't need to be loud to lead. Just build quietly, and let your results echo.",
      isFeatured: true, isVerified: true, viewCount: 8100, associatedPollCount: 3,
    },
    {
      name: "Rami Shaar",
      headline: "Co-Founder of Washmen — cancelled a sponsorship over Gaza and turned down TV to stay clean. That's how he builds.",
      role: "Co-Founder & CEO", company: "Washmen", sector: "Consumer Tech & Urban Logistics",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Rami built Washmen into one of Dubai's most trusted consumer tech brands. Known as much for his principled public stances as for his product — including walking away from sponsorships and TV deals over ethical lines.",
      story: "Rami built Washmen into one of Dubai's most trusted consumer tech brands. Known as much for his principled public stances as for his product — including walking away from sponsorships and TV deals over ethical lines.",
      lessonsLearned: [], quote: "Your silence costs more than any Stripe fee. Act like it.",
      isFeatured: true, isVerified: true, viewCount: 11800, associatedPollCount: 4,
    },
    {
      name: "Maysa Jalbout",
      headline: "Palestinian refugee twice over by 16. Founding CEO of the Abdulla Al Ghurair Foundation. Brookings Fellow. She built pathways where none existed.",
      role: "Nonresident Fellow", company: "Brookings Institution / AGFE", sector: "Education & Philanthropy",
      country: "International", city: "Dubai", imageUrl: null,
      summary: "Maysa's personal displacement shaped a 20+ year career at the intersection of education, refugee policy, and philanthropy — founding and leading the Abdulla Al Ghurair Foundation for Education and advising world leaders across the World Bank, UNHCR, and Brookings.",
      story: "Maysa's personal displacement shaped a 20+ year career at the intersection of education, refugee policy, and philanthropy — founding and leading the Abdulla Al Ghurair Foundation for Education and advising world leaders across the World Bank, UNHCR, and Brookings.",
      lessonsLearned: [], quote: "Your greatest strength may lie in the story you were once afraid to tell.",
      isFeatured: true, isVerified: true, viewCount: 10600, associatedPollCount: 3,
    },
    {
      name: "Dubai Abulhoul",
      headline: "Founder of Fiker Institute — building the Arab world's first serious geopolitical think tank",
      role: "Founder", company: "Fiker Institute", sector: "Foreign Policy & Diplomacy",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Dubai is a Rhodes Scholar (Oxford, Diplomacy & Global Governance) who founded Fiker Institute to ensure Arab voices shape global policy — not just respond to it. Has debated Macron and sits on the WEF Global Council and COP28 Advisory Board.",
      story: "Dubai is a Rhodes Scholar (Oxford, Diplomacy & Global Governance) who founded Fiker Institute to ensure Arab voices shape global policy — not just respond to it. Has debated Macron and sits on the WEF Global Council and COP28 Advisory Board.",
      lessonsLearned: [], quote: "The region does not need more voices. It needs voices that carry weight.",
      isFeatured: true, isVerified: true, viewCount: 13400, associatedPollCount: 5,
    },
    {
      name: "Dr. Samah Jabr",
      headline: "Palestinian psychiatrist. Treats trauma under occupation. Published globally. Refuses to separate care from context.",
      role: "Head of Mental Health Unit", company: "Palestinian Ministry of Health / Tawassol Center / George Washington University", sector: "Healthcare & Human Rights",
      country: "Palestine", city: "Ramallah", imageUrl: null,
      summary: "Dr. Samah has spent 20+ years building mental health infrastructure for Palestinians, teaching that healing is not just therapeutic — it is political, cultural, and an act of resistance. Author of Derrière les fronts.",
      story: "Dr. Samah has spent 20+ years building mental health infrastructure for Palestinians, teaching that healing is not just therapeutic — it is political, cultural, and an act of resistance. Author of Derrière les fronts.",
      lessonsLearned: [], quote: "We must learn to see our scars as stories, not symptoms.",
      isFeatured: true, isVerified: true, viewCount: 11200, associatedPollCount: 2,
    },
    {
      name: "Farah Foustok",
      headline: "Founding Partner of ALARA Partners — 30 years in finance, and she's still the loudest voice in the room for what matters",
      role: "Founding Partner", company: "ALARA Partners", sector: "Finance & Impact Investing",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Farah spent nearly a decade leading Lazard Asset Management in the Middle East before founding ALARA Partners. Known as much for her investment discipline as for her unflinching public stance on justice in Gaza.",
      story: "Farah spent nearly a decade leading Lazard Asset Management in the Middle East before founding ALARA Partners. Known as much for her investment discipline as for her unflinching public stance on justice in Gaza.",
      lessonsLearned: [], quote: "Invest in things your children will be proud you stood for.",
      isFeatured: true, isVerified: true, viewCount: 9900, associatedPollCount: 4,
    },
    {
      name: "Ghassan R. Haddad",
      headline: "Chief of Staff to Lebanon's Minister of Tourism. Former Uber and Lime policy chief. Once helped get Macron to meet with Uber.",
      role: "Chief of Staff to Minister of Tourism", company: "Lebanese Ministry of Tourism", sector: "Public Policy & Digital Governance",
      country: "Lebanon", city: "Beirut", imageUrl: null,
      summary: "Ghassan navigated some of Uber's most sensitive regulatory battles across MENA, France, and Southern Europe, then became EMEA VP at Lime, and now applies it all to Lebanon's economic recovery as the Minister's Chief of Staff.",
      story: "Ghassan navigated some of Uber's most sensitive regulatory battles across MENA, France, and Southern Europe, then became EMEA VP at Lime, and now applies it all to Lebanon's economic recovery as the Minister's Chief of Staff.",
      lessonsLearned: [], quote: "If you want to modernize a system, start by understanding who it is failing and why.",
      isFeatured: false, isVerified: true, viewCount: 4900, associatedPollCount: 3,
    },
    {
      name: "Leila Kaissi",
      headline: "Principal at Adams Street Partners — a decade at Gulf Capital and now managing investments on a global platform",
      role: "Principal", company: "Adams Street Partners", sector: "Private Equity & Finance",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Leila spent 10 years at Gulf Capital driving investment strategy before joining Adams Street Partners, bringing deep MENA deal expertise to a global private equity platform.",
      story: "Leila spent 10 years at Gulf Capital driving investment strategy before joining Adams Street Partners, bringing deep MENA deal expertise to a global private equity platform.",
      lessonsLearned: [], quote: "Private equity is more than just capital. It is conviction, consistency, and the courage to back what others overlook.",
      isFeatured: false, isVerified: true, viewCount: 4400, associatedPollCount: 3,
    },
    {
      name: "Rateel Al Shehri",
      headline: "Saudi Arabia's top influencer. She's 13.",
      role: "Creator & Influencer", company: "Independent", sector: "Media & Social Influence",
      country: "Saudi Arabia", city: "Riyadh", imageUrl: null,
      summary: "Rateel is Saudi Arabia's most-followed youth creator, using her platform to inspire millions of young Arabs with positive messaging, resilience, and authenticity.",
      story: "Rateel is Saudi Arabia's most-followed youth creator, using her platform to inspire millions of young Arabs with positive messaging, resilience, and authenticity.",
      lessonsLearned: [], quote: "Authenticity is your strength. Be true to yourself.",
      isFeatured: false, isVerified: false, viewCount: 7200, associatedPollCount: 2,
    },
    {
      name: "Adam El Rafey",
      headline: "Enrolled in university at 12. TED Talk at 8. Youngest student in UAE history.",
      role: "Student & Change Advocate", company: "University of Wollongong Dubai", sector: "Education & Youth",
      country: "UAE", city: "Dubai", imageUrl: null,
      summary: "Adam became the UAE's youngest university student at 12, delivered a TEDx talk at 8, and was recognized as a 25 Under 25 Global Changemaker at 11. Passionate about sustainable urban mobility.",
      story: "Adam became the UAE's youngest university student at 12, delivered a TEDx talk at 8, and was recognized as a 25 Under 25 Global Changemaker at 11. Passionate about sustainable urban mobility.",
      lessonsLearned: [], quote: "Never let your age define your potential — let your ideas and actions lead the way.",
      isFeatured: false, isVerified: true, viewCount: 5600, associatedPollCount: 2,
    },
    {
      name: "AlDhabi AlMheiri",
      headline: "Published her first book at 10. Now holds 3 Guinness World Records. Still in school.",
      role: "Founder, Columnist & Advocate", company: "Rainbow Chimney", sector: "EdTech & Publishing",
      country: "UAE", city: "Abu Dhabi", imageUrl: null,
      summary: "AlDhabi founded Rainbow Chimney publishing at 10, now holds 3 Guinness World Records, writes columns in two publications, and advocates for children with additional needs.",
      story: "AlDhabi founded Rainbow Chimney publishing at 10, now holds 3 Guinness World Records, writes columns in two publications, and advocates for children with additional needs.",
      lessonsLearned: [], quote: "Believe in the power of children to create change — they are not just our future; they are our now.",
      isFeatured: false, isVerified: true, viewCount: 4800, associatedPollCount: 2,
    },
  ]).returning();

  console.log(`Inserted ${profiles.length} profiles`);

  // ── Poll-Profile index helpers ────────────────────────────────────────────────
  // profiles array is 0-indexed matching insertion order above
  const pid = (i: number) => profiles[i].id;

  // ── Polls ─────────────────────────────────────────────────────────────────────
  const pollData = [
    {
      question: "Your job will still exist in 5 years. Be honest.",
      context: "AI isn't coming for jobs — it already has. The question is whether you've accepted it yet.",
      category: "AI & The Future", categorySlug: "ai-future",
      tags: ["AI", "Jobs", "Future of Work", "Career"],
      pollType: "multiple_choice", isFeatured: true, isEditorsPick: true,
      options: ["Yes, I'm irreplaceable", "Probably not and I'm doing nothing about it", "Probably not but I have a plan", "I genuinely don't know"],
      votes: [1200, 2800, 1900, 3100],
      relatedProfileIds: [pid(5), pid(26), pid(41)],  // Ghaith, Amjad Masad, Rami Salman
    },
    {
      question: "The most dangerous thing AI did wasn't take jobs — it exposed how many jobs were already pointless.",
      context: "Millions of roles existed because no alternative existed. Now there is one.",
      category: "AI & The Future", categorySlug: "ai-future",
      tags: ["AI", "Work", "Hot Take"],
      pollType: "hot_take", isFeatured: false, isEditorsPick: true,
      options: ["Brutally accurate", "Too harsh — most jobs have real value"],
      votes: [4200, 1100],
      relatedProfileIds: [pid(26), pid(5), pid(18)],  // Amjad, Ghaith, Fadi Kanaan
    },
    {
      question: "Would you rather be managed by an AI or a mediocre human manager?",
      context: null,
      category: "AI & The Future", categorySlug: "ai-future",
      tags: [], pollType: "binary", isFeatured: false, isEditorsPick: false,
      options: ["Give me the AI", "I'll take the human, flaws and all"],
      votes: [3800, 1400],
      relatedProfileIds: [pid(41), pid(18), pid(26)],  // Rami Salman, Fadi Kanaan, Amjad
    },
    {
      question: "If AI replaces your role, whose fault is it?",
      context: null,
      category: "AI & The Future", categorySlug: "ai-future",
      tags: [], pollType: "multiple_choice", isFeatured: false, isEditorsPick: true,
      options: ["Mine — I didn't upskill fast enough", "My company — they didn't train or warn me", "Nobody's — this was always going to happen", "The government — they should have regulated this"],
      votes: [2100, 1600, 2800, 900],
      relatedProfileIds: [pid(26), pid(5), pid(41)],  // Amjad, Ghaith, Rami Salman
    },
    {
      question: "Wasta still beats talent in this region. Agree?",
      context: "You can be the best in the room and still lose to someone's cousin. Has anything actually changed?",
      category: "Work & Careers", categorySlug: "work-careers",
      tags: ["Wasta", "Talent", "Culture", "Careers"],
      pollType: "multiple_choice", isFeatured: false, isEditorsPick: true,
      options: ["100% still true", "Getting better but slowly", "Depends on the country", "It's a myth — merit wins if you're good enough"],
      votes: [3400, 2100, 1800, 600],
      relatedProfileIds: [pid(6), pid(43), pid(32)],  // Walid Faza, Tala Al Jabri, Abe Seksek
    },
    {
      question: "The real brain drain isn't people leaving — it's people staying and checking out.",
      context: "Physically present. Emotionally gone. Building nothing. The quiet resignation nobody talks about.",
      category: "Work & Careers", categorySlug: "work-careers",
      tags: [], pollType: "hot_take", isFeatured: false, isEditorsPick: false,
      options: ["This is the actual crisis", "No — people leaving is still the bigger problem"],
      votes: [3900, 1200],
      relatedProfileIds: [pid(21), pid(32), pid(44)],  // Maher Kaddoura, Abe Seksek, Nafez Dakkak
    },
    {
      question: "Most 'founders' in this region are consultants with a pitch deck. Change my mind.",
      context: null,
      category: "Startups & Venture", categorySlug: "startups-venture",
      tags: ["Founders", "Startups", "Hot Take"],
      pollType: "hot_take", isFeatured: false, isEditorsPick: true,
      options: ["Can't — this is painfully accurate", "Wrong — real builders are everywhere, just underreported"],
      votes: [2800, 1900],
      relatedProfileIds: [pid(6), pid(25), pid(43)],  // Walid Faza, Laith Zraikat, Tala Al Jabri
    },
    {
      question: "The next unicorn from this region will come from...",
      context: null,
      category: "Startups & Venture", categorySlug: "startups-venture",
      tags: [], pollType: "multiple_choice", isFeatured: false, isEditorsPick: false,
      options: ["Cairo", "Riyadh", "Dubai", "Somewhere nobody's watching yet"],
      votes: [2100, 2400, 1800, 3200],
      relatedProfileIds: [pid(25), pid(24), pid(32)],  // Laith Zraikat, Karima El Hakim, Abe Seksek
    },
    {
      question: "LinkedIn in the Arab world is just a brag board. Nobody posts their failures.",
      context: null,
      category: "Culture & Identity", categorySlug: "culture-identity",
      tags: ["LinkedIn", "Culture", "Authenticity"],
      pollType: "hot_take", isFeatured: false, isEditorsPick: true,
      options: ["Facts — it's completely performative", "Disagree — it's improving", "Same everywhere, not just here"],
      votes: [4100, 600, 1800],
      relatedProfileIds: [pid(16), pid(39), pid(40)],  // Loulou Khazen Baz, Sara Hamdan, Nader Baker
    },
    {
      question: "Arab parents would rather their kid be a doctor than a founder. Can you blame them?",
      context: "Founding a company in this region means navigating systems designed for established players. The risk is real.",
      category: "Culture & Identity", categorySlug: "culture-identity",
      tags: [], pollType: "multiple_choice", isFeatured: false, isEditorsPick: false,
      options: ["Can't blame them — the odds are brutal", "This mindset is exactly why we fall behind", "It's changing with the new generation"],
      votes: [2200, 2800, 1900],
      relatedProfileIds: [pid(21), pid(2), pid(22)],  // Maher Kaddoura, Raya Bidshahri, Badr Ward
    },
    {
      question: "We're becoming obsessed with looking successful instead of actually being successful.",
      context: null,
      category: "Culture & Identity", categorySlug: "culture-identity",
      tags: [], pollType: "hot_take", isFeatured: false, isEditorsPick: false,
      options: ["This is the defining disease of our generation", "Disagree — ambition drives real outcomes too"],
      votes: [3600, 1100],
      relatedProfileIds: [pid(16), pid(40), pid(13)],  // Loulou, Nader Baker, Saad Abu Touq
    },
    {
      question: "The diaspora built half of what the Middle East is proud of — and gets none of the credit.",
      context: null,
      category: "Culture & Identity", categorySlug: "culture-identity",
      tags: [], pollType: "binary", isFeatured: false, isEditorsPick: false,
      options: ["True — and it needs to change", "False — the credit is there if you look"],
      votes: [3800, 900],
      relatedProfileIds: [pid(7), pid(21), pid(39)],  // Majid Al Ansari, Maher Kaddoura, Sara Hamdan
    },
    {
      question: "Egypt is one bad IMF negotiation away from something really ugly.",
      context: null,
      category: "Finance & Economy", categorySlug: "finance-economy",
      tags: ["Egypt", "IMF", "Economy", "Crisis"],
      pollType: "multiple_choice", isFeatured: false, isEditorsPick: true,
      options: ["Agree — the fundamentals are broken", "Disagree — Egypt always finds a way", "It's already ugly, we just aren't saying it"],
      votes: [2400, 1200, 2900],
      relatedProfileIds: [pid(24), pid(36), pid(49)],  // Karima El Hakim, Mohamed Aboulnaga, Ambareen Musa
    },
    {
      question: "Dubai property in 2025 — still inflating or finally about to correct?",
      context: null,
      category: "Finance & Economy", categorySlug: "finance-economy",
      tags: [], pollType: "multiple_choice", isFeatured: false, isEditorsPick: false,
      options: ["Still inflating — demand is structural", "Correction is coming within 2 years", "Already correcting, quietly"],
      votes: [1800, 2100, 1400],
      relatedProfileIds: [pid(31), pid(63), pid(52)],  // Mark Chahwan, Leila Kaissi, Noelle Al-Jaweini
    },
    {
      question: "In 10 years, the most valuable skill in the Middle East will be...",
      context: null,
      category: "AI & The Future", categorySlug: "ai-future",
      tags: [], pollType: "multiple_choice", isFeatured: false, isEditorsPick: true,
      options: ["Knowing how to work with AI", "Human judgment and emotional intelligence", "Arabic fluency at a professional level", "Knowing the right people"],
      votes: [3200, 2400, 1100, 1800],
      relatedProfileIds: [pid(26), pid(2), pid(5)],  // Amjad Masad, Raya Bidshahri, Ghaith
    },
    {
      question: "A 22-year-old in Cairo with a laptop has more opportunity than their parents ever did. True or false?",
      context: "The internet removed gatekeepers. But it also created new ones. Algorithms, English fluency, access to capital.",
      category: "AI & The Future", categorySlug: "ai-future",
      tags: [], pollType: "multiple_choice", isFeatured: false, isEditorsPick: false,
      options: ["True — the tools exist, excuses don't", "False — structural barriers are worse than ever", "True for some, completely false for most"],
      votes: [2100, 1600, 3400],
      relatedProfileIds: [pid(24), pid(36), pid(29)],  // Karima El Hakim, Mohamed Aboulnaga, Dina Sam'an
    },
    {
      question: "Saudi money changed the Gulf startup scene. Not always for the better.",
      context: null,
      category: "Startups & Venture", categorySlug: "startups-venture",
      tags: [], pollType: "hot_take", isFeatured: false, isEditorsPick: false,
      options: ["Agree — it inflated valuations and created dependency", "Disagree — it unlocked a decade of real growth"],
      votes: [2600, 1800],
      relatedProfileIds: [pid(43), pid(6), pid(34)],  // Tala Al Jabri, Walid Faza, Dr. Sara Althari
    },
    {
      question: "If your startup needs a government contract to survive Year 1, is it really a startup?",
      context: null,
      category: "Startups & Venture", categorySlug: "startups-venture",
      tags: [], pollType: "multiple_choice", isFeatured: false, isEditorsPick: false,
      options: ["No — that's a services business with a deck", "Yes — working with government is just a distribution strategy", "Depends entirely on the sector"],
      votes: [2200, 1400, 2800],
      relatedProfileIds: [pid(32), pid(25), pid(6)],  // Abe Seksek, Laith Zraikat, Walid Faza
    },
  ];

  for (const poll of pollData) {
    const [inserted] = await db.insert(pollsTable).values({
      question: poll.question,
      context: poll.context,
      category: poll.category,
      categorySlug: poll.categorySlug,
      tags: poll.tags,
      pollType: poll.pollType,
      isFeatured: poll.isFeatured,
      isEditorsPick: poll.isEditorsPick,
      relatedProfileIds: poll.relatedProfileIds,
    }).returning();

    await db.insert(pollOptionsTable).values(
      poll.options.map((text, i) => ({
        pollId: inserted.id,
        text,
        voteCount: poll.votes[i] ?? 0,
      }))
    );
  }

  console.log(`Inserted ${pollData.length} polls`);
  console.log("Seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
